[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
game_store = "7Z9MDRw8oALQyZQGF6LDh9G1t9mQvN3pFsuXzfb31MnS"
pgc1 = "3ZbX4ehgZYZ6TXARcF8tVsJmjxNoB5D67PkXiXqjk1JA"
registry = "CrHcKzUfp9ykApDFt5tBzs1MK41QAjbrPVxdoYifzE2r"

[programs.localnet]
game_store = "7Z9MDRw8oALQyZQGF6LDh9G1t9mQvN3pFsuXzfb31MnS"
pgc1 = "3ZbX4ehgZYZ6TXARcF8tVsJmjxNoB5D67PkXiXqjk1JA"
registry = "CrHcKzUfp9ykApDFt5tBzs1MK41QAjbrPVxdoYifzE2r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
