[toolchain]
package_manager = "pnpm"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
game_store = "6gTd8TQ9NiC7yxBfGWBzH1aWdk77fg779nUJhYTrEsPd"
pgl1 = "DzDbFZXZsmFFv1mMFimLaBjAQi7Z5gUaQ61qcDuR6Kor"
registry = "DCYPxPtnVeBgy56SYMT6GPBMJp8NJNLmE46QfHYqCgGL"

[programs.localnet]
game_store = "6gTd8TQ9NiC7yxBfGWBzH1aWdk77fg779nUJhYTrEsPd"
pgl1 = "DzDbFZXZsmFFv1mMFimLaBjAQi7Z5gUaQ61qcDuR6Kor"
registry = "DCYPxPtnVeBgy56SYMT6GPBMJp8NJNLmE46QfHYqCgGL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
