[toolchain]
anchor_version = "0.32.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
game_store = "5fcEaw6eMUeCLzhEqzqqL5HczQm1yj9GZjQQeqL66h5g"
pgl1 = "GAt9373oMr9Ykc1Auudy4wNR9PL7tRPaXMwSKiYpyQpP"
registry = "G2XvhJoEkjiu3rCysaAjTuDj1dT5NAS8RNUTVi9H7ggE"

[programs.localnet]
game_store = "5fcEaw6eMUeCLzhEqzqqL5HczQm1yj9GZjQQeqL66h5g"
pgl1 = "GAt9373oMr9Ykc1Auudy4wNR9PL7tRPaXMwSKiYpyQpP"
registry = "G2XvhJoEkjiu3rCysaAjTuDj1dT5NAS8RNUTVi9H7ggE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
