use quasar_lang::prelude::*;

#[error_code]
pub enum StoreError {
    Unauthorized,
    InvalidPlatformFeeBps,
    InvalidDefaultReferralBps,
    InvalidMaxReferralBps,
    ReferralAboveMax,
    SourceProgramNotAuthorized,
    RegistryProgramNotAuthorized,
    PaymentTokenNotAllowed,
    PaymentTokenDisabled,
    InvalidPrice,
    PriceNotFound,
    StoreGameInactive,
    GameNotActive,
    GameNotRegistered,
    AlreadyOwned,
    InvalidDiscountBps,
    InvalidDiscountWindow,
    InvalidReferralBps,
    MathOverflow,
    InvalidPaymentAmount,
    UnsupportedSourceGameOwner,
    RegistryGameMismatch,
    PaymentFailed,
    LicenseMintFailed,
    MissingReferrerTokenAccount,
    InvalidReferrerTokenAccount,
    InvalidTreasury,
    InvalidStoreActor,
    GamePaymentOptionMismatch,
    InvalidRole,
    InsufficientRole,
}
