pub mod add_payment_token;
pub mod close_registry_game;
pub mod create_game_and_register;
pub mod initialize_registry;
pub mod remove_payment_token;
pub mod set_publish_grant;
pub mod set_treasury;
pub mod update_game_status;
pub mod update_payment_token;

pub use add_payment_token::*;
pub use close_registry_game::*;
pub use create_game_and_register::*;
pub use initialize_registry::*;
pub use remove_payment_token::*;
pub use set_publish_grant::*;
pub use set_treasury::*;
pub use update_game_status::*;
pub use update_payment_token::*;
